-- ============================================================================
--  Kub·House — schema for a self-hosted PostgreSQL (no Supabase).
-- ----------------------------------------------------------------------------
--  This replaces the Supabase project: plain Postgres + the FastAPI backend
--  (api.sme-ta.ru) now owns auth (JWT) and the data API. There are no
--  anon/authenticated roles and no RLS — the backend connects as one DB user
--  and enforces access in code (JWT for the operator, secret slug/token for the
--  public vendor/client pages).
--
--  Apply once on a fresh database:
--      psql "$DATABASE_URL" -f db/schema.sql
--
--  Columns were reconstructed from the frontend's read/write usage. If you have
--  a real dump from the old Supabase project, diff it against this file and add
--  any columns you customized:
--      pg_dump --schema-only --no-owner --no-privileges "<supabase-conn>" > old.sql
-- ============================================================================

-- updated_at auto-touch (objects/contractors/user_catalog don't send it) -------
create or replace function kh_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- Operator accounts (replaces Supabase Auth) ---------------------------------
create table if not exists kh_users (
  id            bigint generated always as identity primary key,
  email         text not null unique,
  password_hash text not null,
  role          text not null default 'estimator',  -- admin | estimator | viewer
  name          text not null default '',           -- ФИО оператора (для аватара/списка)
  created_at    timestamptz not null default now()
);
-- Existing databases (table already created): apply once by hand —
--   alter table kh_users add column if not exists role text not null default 'estimator';
--   alter table kh_users add column if not exists name text not null default '';

-- Projects / objects ---------------------------------------------------------
create table if not exists kh_objects (
  id         text primary key,
  name       text,
  address    text,
  area       numeric,
  stage      text,
  date       text,
  budget     numeric,
  client     text,
  note       text,
  status     text,
  files      jsonb default '[]'::jsonb,
  updated_at timestamptz not null default now()
);
drop trigger if exists kh_objects_touch on kh_objects;
create trigger kh_objects_touch before update on kh_objects
  for each row execute function kh_touch_updated_at();

-- Operator's custom catalog (keyed by name+unit) -----------------------------
create table if not exists kh_user_catalog (
  name       text not null,
  unit       text not null default '',
  unit_price numeric default 0,
  updated_at timestamptz not null default now(),
  primary key (name, unit)
);
drop trigger if exists kh_user_catalog_touch on kh_user_catalog;
create trigger kh_user_catalog_touch before update on kh_user_catalog
  for each row execute function kh_touch_updated_at();

-- Hidden catalog keys (soft-delete tracking) ---------------------------------
create table if not exists kh_hidden (
  key text primary key
);

-- Calendar events ------------------------------------------------------------
create table if not exists kh_events (
  id    bigint primary key,
  date  text,
  time  text,
  title text
);

-- Contractors / vendors (slug is the public vendor-page key) -----------------
create table if not exists kh_contractors (
  id         text primary key,
  name       text,
  email      text,
  phone      text,
  type       text,
  org        text,
  website    text,
  slug       text unique,
  file_name  text,
  file_size  bigint,
  file_time  text,
  updated_at timestamptz not null default now()
);
drop trigger if exists kh_contractors_touch on kh_contractors;
create trigger kh_contractors_touch before update on kh_contractors
  for each row execute function kh_touch_updated_at();

-- Vendor price lists (public vendor page writes here, scoped by slug) ---------
create table if not exists kh_vendor_prices (
  id          bigint generated by default as identity primary key,
  vendor_slug text not null,
  vendor_name text,
  name        text not null,
  unit        text default '',
  qty         numeric,
  unit_price  numeric default 0,
  source_file text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (vendor_slug, name, unit)
);
create index if not exists kh_vendor_prices_slug_idx on kh_vendor_prices (vendor_slug);

-- Client-facing estimates (public client page reads/writes by token) ----------
create table if not exists kh_client_estimates (
  token      text primary key,
  rows       jsonb default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Price-source store configs -------------------------------------------------
create table if not exists kh_stores (
  id         text primary key,
  url        text,
  name       text,
  host       text,
  favicon    text,
  method     text,
  currency   text,
  found      boolean,
  confidence numeric,
  note       text,
  samples    jsonb,
  active     boolean,
  search_url text,
  added_at   timestamptz default now(),
  last_check timestamptz
);

-- Файлы, прикреплённые к объектам (IFC-модели, чертежи и т.п.). Хранятся на
-- диске бэкенда (см. backend/object_files.py), в этой таблице — только
-- метаданные. Скачивать клиенту не даём (стрим без Content-Disposition).
create table if not exists kh_object_files (
  id            text primary key,            -- uuid строки
  object_id     text not null references kh_objects(id) on delete cascade,
  filename      text not null,
  size_bytes    bigint not null,
  content_type  text,
  uploaded_at   timestamptz not null default now(),
  uploaded_by   text                          -- email оператора (для аудита)
);
create index if not exists kh_object_files_obj on kh_object_files (object_id);
